name: "🐞 Bug report"
description: "Report a reproducible bug or regression"
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Short description of the bug"
      placeholder: "The app crashes when I click Save"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "List the steps to reproduce the issue"
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What should have happened?"
  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      placeholder: "What actually happened?"
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Web