name: "🚀 Feature request"
description: "Propose a new feature or improvement"
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "We love ideas! Please describe your proposal clearly."
  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      placeholder: "I'm frustrated when..."
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      placeholder: "It would be great if..."
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives you've considered"
  - type: input
    id: context
    attributes:
      label: "Additional context"
      placeholder: "Any screenshots, links, or references"